@token = VL6-hrQm9Zfa8JEfGG07RUQIfIjW73gsn9QtrRhVs8I=

### Create Coach
POST http://localhost:8080/api/coaches
Content-Type: application/json

{
  "username": "abfe",
  "password": "Test123!"
}


### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "user2",
  "password": "Admin123!"
}

### Logout
POST http://localhost:8080/api/logout
Authorization: Bearer {{token}}



### Create Characteristic
POST http://localhost:8080/api/athletes/3/characteristics
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "date": "01-01-2000",
  "weight" : 1.0,
  "height" : 1,
  "calories" : 1,
  "waist" : 1,
  "arm" : 1,
  "thigh" : 1,
  "tricep" : 1.0,
  "abdominal" : 1.0
}


### Remove
DELETE http://localhost:8080/api/athletes/3/characteristics/01-01-2000
Authorization: Bearer {{token}}




### Get Characteristic
GET http://localhost:8080/api/athletes/1/characteristics/946684800000
Authorization: Bearer {{token}}



### Get athletes
GET http://localhost:8080/api/athletes
Authorization: Bearer {{token}}

### Get athlete
GET http://localhost:8080/api/athletes/3
Authorization: Bearer {{token}}


### create Athlete
POST http://localhost:8080/api/athletes
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="input"
Content-Type: application/json

{
  "name": "asdasdasdasd",
  "birthDate": "01-01-2025"
}
--boundary--



### Generate Code
POST http://localhost:8080/api/athletes/6/code
Authorization: Bearer {{token}}



### get activities
GET http://localhost:8080/api/athletes/3/activities
Authorization: Bearer {{token}}


### get athletes
GET http://localhost:8080/api/athletes
Authorization: Bearer {{token}}

### create calendar
POST http://localhost:8080/api/athletes/3/calendar
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "mesocycles": [
    {
      "id": null,
      "startTime": 1745442324000,
      "endTime": 1747442379000,
      "microcycles": [
        {
          "id": null,
          "startTime": 1745442379000,
          "endTime": 1746442379000
        },
        {
          "id": null,
          "startTime": 1746442379000,
          "endTime": 1747442379000
        }
      ]
    }
  ]
}

### get calendar
GET http://localhost:8080/api/athletes/3/calendar?type=wasdsadasd
Authorization: Bearer {{token}}



### Get Gym Workout
GET http://localhost:8080/api/gym/31
Authorization: Bearer {{token}}

### Create Water Maneuver
POST http://localhost:8080/api/water/maneuver
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "other name"
}


### Get Water Maneuvers
GET http://localhost:8080/api/water/maneuver
Authorization: Bearer {{token}}




### Get water activity
GET http://localhost:8080/api/water/28
Authorization: Bearer {{token}}



### Get water activities
GET http://localhost:8080/api/athletes/3/water
Authorization: Bearer {{token}}

